// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUlj-_E2qHu-w6h8dtpB_OycALZkjBiuc',
    appId: '1:342652815802:android:c73709ddd39cbdbe35b583',
    messagingSenderId: '342652815802',
    projectId: 'productcatalog-ca642',
    databaseURL: 'https://productcatalog-ca642-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'productcatalog-ca642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALUBPTvbtA0EmSzzQLGfqCyb_gBKmxG0k',
    appId: '1:342652815802:ios:90264be5f73a829835b583',
    messagingSenderId: '342652815802',
    projectId: 'productcatalog-ca642',
    databaseURL: 'https://productcatalog-ca642-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'productcatalog-ca642.appspot.com',
    iosClientId: '342652815802-1k5pcvphrqmluddlvpbbi94sms999gm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloFlutter',
  );
}
